version: "3.1"
services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # test:
  #   build: ./test
  #   ports: ["49160:8080"]

  
  # test2:
  #   build: ./test2
  #   ports: ["49161:8080"]
  
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports: ["8080:8080"]

    nginx:
      image: nginx
      volumes: 
        - ./reverse-proxy/nginx/conf:/etc/nginx/conf.d/
        # - ./reverse-proxy:/etc/ssl/private
      ports:
        - 8080:80
        - 443:443