version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports: ["9000:8080"]

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./reverse-proxy/nginx:/etc/nginx
      # - ./reverse-proxy:/etc/ssl/private
    ports:
      - 8080:80
      - 443:443

  test:
    build: ./test
    restart: always
    volumes:
      - ./test:/usr/src/app
    ports: ["49160:8080"]

  test2:
    build: ./test2
    restart: always
    volumes:
      - ./test2:/usr/src/app
    ports: ["49161:8080"]
